version: "3.9"

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:123456@db:5432/app
      NODE_OPTIONS: --dns-result-order=ipv4first
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: